version: '3'
services:
  package:
    build:
      context: ./package
      dockerfile: Dockerfile
    volumes:
      - app-volume:/home/pkhramchenkov/boxfuse-sample-java-war-hello/target/
  prod:
    build:
      context: ./prod
      dockerfile: Dockerfile
    depends_on:
      - package
    ports:
      - "8080:8080"
    volumes:
      - app-volume:/usr/local/tomcat/webapps/
volumes:
  app-volume:
